
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase'; // Updated import to use our extended types

const SUPABASE_URL = "https://jppeztsbsecizzpdxugk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwcGV6dHNic2VjaXp6cGR4dWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjQwMDcsImV4cCI6MjA1NzY0MDAwN30.tWor5HXfGu6Z0BphIqw6kK53WovqC1S6JMUWqiBD0DM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
